# Generated by Django 3.2 on 2021-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('bird_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('Original_Name', models.CharField(max_length=50)),
                ('Biological_Name', models.CharField(max_length=50)),
                ('Cat', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
                ('image1', models.ImageField(default='', upload_to='FindBird/image1')),
                ('image2', models.ImageField(default='', upload_to='FindBird/image2')),
                ('map', models.ImageField(default='', upload_to='FindBird/map')),
            ],
        ),
    ]
