# Generated by Django 3.2 on 2021-05-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='character',
            new_name='Bird',
        ),
    ]
