# Generated by Django 3.2 on 2021-05-08 10:34

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0003_auto_20210507_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='map',
            new_name='map1',
        ),
        migrations.AddField(
            model_name='bird',
            name='audio',
            field=audiofield.fields.AudioField(default='', upload_to='FindBird/audio'),
        ),
    ]
