# Generated by Django 3.2 on 2021-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0004_auto_20210508_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='audio',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
