# Generated by Django 3.2 on 2021-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0005_alter_bird_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='audio',
        ),
    ]
