# Generated by Django 3.2 on 2021-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0007_bird_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='imgdesc1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bird',
            name='mapdesc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bird',
            name='recdesc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
