# Generated by Django 3.2 on 2021-05-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0008_auto_20210510_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Cat',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='imgdesc1',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='mapdesc',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='recdesc',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='record',
        ),
    ]
