# Generated by Django 3.2 on 2021-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBird', '0010_bird_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='search_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
